// Auto-generated by: npm run voiceover -- PaperRokmotionStart
// Regenerate after changing narration script.

export const paperRokmotionStartVoiceover = {
  enabled: true,
  audioFile: "voiceover/PaperRokmotionStart/narration.mp3",
  durationInSeconds: 30.093,
} as const;
