// Auto-generated by: npm run voiceover -- RokmotionTutorial
// Regenerate after changing narration script.

export const rokmotionTutorialVoiceover = {
  enabled: true,
  audioFile: "voiceover/RokmotionTutorial/narration.mp3",
  durationInSeconds: 23.592,
} as const;
