import * as dotenv from "dotenv";
import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";
import { scenePlanSchema, type ScenePlan } from "../src/lib/video-modes";

dotenv.config();

type Mode = "user-voiceover" | "video-to-video";

const probeDuration = (filePath: string): number => {
  try {
    const out = execSync(
      `ffprobe -v quiet -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${filePath}"`,
      { encoding: "utf-8" },
    ).trim();
    return parseFloat(out);
  } catch {
    console.warn("ffprobe not available — using 30s default duration");
    return 30;
  }
};

const copyFile = (src: string, dest: string) => {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
};

const extractAudio = (videoPath: string, audioOut: string) => {
  try {
    execSync(
      `ffmpeg -y -i "${videoPath}" -vn -acodec libmp3lame -q:a 2 "${audioOut}"`,
      { stdio: "pipe" },
    );
    return true;
  } catch {
    console.warn("ffmpeg not available — skipping audio extraction");
    return false;
  }
};

const writeMeta = (projectId: string, data: Record<string, unknown>) => {
  const metaPath = path.join(
    process.cwd(),
    "src",
    "uploads",
    `${projectId}.meta.ts`,
  );
  fs.mkdirSync(path.dirname(metaPath), { recursive: true });
  const exportName = projectId.charAt(0).toLowerCase() + projectId.slice(1) + "Upload";

  const content = `// Auto-generated by: npm run import-assets
export const ${exportName} = ${JSON.stringify(data, null, 2)} as const;
`;
  fs.writeFileSync(metaPath, content);
};

const parseArgs = () => {
  const args = process.argv.slice(2);
  const get = (flag: string) => {
    const i = args.indexOf(flag);
    return i === -1 ? undefined : args[i + 1];
  };

  return {
    mode: get("--mode") as Mode | undefined,
    project: get("--project"),
    audio: get("--audio"),
    video: get("--video"),
  };
};

const main = () => {
  const { mode, project, audio, video } = parseArgs();

  if (!mode || !project) {
    console.error(`Usage:
  npm run import-assets -- --mode user-voiceover --project <id> --audio <path>
  npm run import-assets -- --mode video-to-video --project <id> --video <path>`);
    process.exit(1);
  }

  const uploadDir = path.join(process.cwd(), "public", "uploads", project);

  if (mode === "user-voiceover") {
    if (!audio) {
      console.error("--audio is required for user-voiceover mode");
      process.exit(1);
    }
    const absAudio = path.resolve(audio);
    const dest = path.join(uploadDir, "voiceover.mp3");
    copyFile(absAudio, dest);
    const duration = probeDuration(dest);

    writeMeta(project, {
      mode: "user-voiceover",
      projectId: project,
      audioFile: `uploads/${project}/voiceover.mp3`,
      durationInSeconds: duration,
    });

    console.log(`Imported voiceover: public/uploads/${project}/voiceover.mp3`);
    console.log(`Duration: ${duration.toFixed(2)}s`);
    return;
  }

  if (mode === "video-to-video") {
    if (!video) {
      console.error("--video is required for video-to-video mode");
      process.exit(1);
    }
    const absVideo = path.resolve(video);
    const dest = path.join(uploadDir, "source.mp4");
    copyFile(absVideo, dest);
    const duration = probeDuration(dest);
    const audioDest = path.join(uploadDir, "source-audio.mp3");
    extractAudio(dest, audioDest);

    const scenePlan: ScenePlan = {
      projectId: project,
      sourceVideo: `uploads/${project}/source.mp4`,
      durationInSeconds: duration,
      scenes: [
        {
          type: "source",
          startSeconds: 0,
          endSeconds: Math.min(8, duration * 0.25),
          title: "Opening",
        },
        {
          type: "animated",
          startSeconds: Math.min(8, duration * 0.25),
          endSeconds: Math.min(18, duration * 0.45),
          title: "Animated overlay",
          pip: {
            enabled: true,
            shape: "circle",
            position: "bottom-right",
            size: 0.2,
          },
        },
        {
          type: "source",
          startSeconds: Math.min(18, duration * 0.45),
          endSeconds: duration,
          title: "Closing",
        },
      ],
    };

    scenePlanSchema.parse(scenePlan);

    const planPath = path.join(uploadDir, "scene-plan.json");
    fs.writeFileSync(planPath, JSON.stringify(scenePlan, null, 2));

    writeMeta(project, {
      mode: "video-to-video",
      projectId: project,
      sourceVideo: scenePlan.sourceVideo,
      audioFile: `uploads/${project}/source-audio.mp3`,
      durationInSeconds: duration,
      scenePlan,
    });

    console.log(`Imported video: public/uploads/${project}/source.mp4`);
    console.log(`Scene plan: public/uploads/${project}/scene-plan.json`);
    console.log(`Duration: ${duration.toFixed(2)}s`);
    console.log("Edit scene-plan.json to adjust animated segments and PiP settings.");
  }
};

main();